import{A as d,S as l,N as u,P as f,K as b,M as m}from"./assets/vendor-DcqEpj7y.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const a of document.querySelectorAll('link[rel="modulepreload"]'))s(a);new MutationObserver(a=>{for(const n of a)if(n.type==="childList")for(const o of n.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&s(o)}).observe(document,{childList:!0,subtree:!0});function r(a){const n={};return a.integrity&&(n.integrity=a.integrity),a.referrerPolicy&&(n.referrerPolicy=a.referrerPolicy),a.crossOrigin==="use-credentials"?n.credentials="include":a.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(a){if(a.ep)return;a.ep=!0;const n=r(a);fetch(a.href,n)}})();(()=>{const e={openModalButton:document.querySelector("[data-mobile-menu-open]"),closeModalButtons:document.querySelectorAll("[data-mobile-menu-close]"),mobileMenu:document.querySelector("[data-mobile-menu]")};e.openModalButton.addEventListener("click",t),e.closeModalButtons.forEach(n=>{n.addEventListener("click",t)});function t(){e.mobileMenu&&(e.mobileMenu.classList.toggle("is-open"),s())}function r(){return e.mobileMenu.classList.contains("is-open")}function s(){r()?document.addEventListener("keydown",a):document.removeEventListener("keydown",a)}function a(n){n.key==="Escape"&&r()&&t()}})();const p={faq:[{question:"Як здійснюється доставка меблів?",answer:"Ми доставляємо замовлення по всій Україні через надійні служби. Термін доставки зазвичай складає 3–7 днів залежно від регіону."},{question:"Чи є можливість вибрати колір або матеріал?",answer:"Так, у багатьох моделях доступні варіанти оббивки та кольорів. Усі доступні опції вказані на сторінці товару."},{question:"Чи можна повернути товар, якщо він не підійшов?",answer:"Так, ви можете повернути товар протягом 14 днів, якщо він не був у користуванні та збережений у первинному вигляді."},{question:"Чи надаєте ви послугу збирання меблів?",answer:"Так, під час оформлення замовлення можна обрати послугу збирання. Наші майстри зберуть меблі у зручний для вас час."},{question:"Як здійснити оплату?",answer:"Ми приймаємо оплату карткою онлайн, банківським переказом або післяплатою при отриманні."}]};document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".accordion-container");if(!e)return;const s=`${new URL("/goit-mebleria/assets/icons-yBS_w1Iq.svg",import.meta.url).href}#chevron-down`,a=p.faq.map(({question:n,answer:o})=>`
    <div class="ac">
      <h3 class="ac-header">
        <button class="ac-trigger" type="button">
          <span>${n}</span>
          <svg class="faq-question-arrow">
            <use href="${s}"></use>
          </svg>
        </button>
      </h3>
      <div class="ac-panel">
        <p class="ac-text">${o}</p>
      </div>
    </div>
    `).join("");e.innerHTML=a,new d(".accordion-container",{duration:400,showMultiple:!1})});function g(e,t){const r=v(e);r&&(t?r.classList.remove("hidden"):r.classList.add("hidden"))}function v(e){return document.querySelector(e)}const w="../img/star-rating.icons.svg";function h(e){const{rateIntValue:t,rateIsHalf:r}=k(e),s=r?"half":"",a=Array.from({length:5},y).join("");return`
    <div class="rating star-svg value-${t} ${s} color-default feedback-star-wrapper">
      <div class="star-container">${a}</div>
    </div>`}function y(){const e=w;return`
    <div class="star">
      <svg class="star-empty"><use href="${e}#star-empty"></use></svg>
      <svg class="star-half"><use href="${e}#star-half"></use></svg>
      <svg class="star-filled"><use href="${e}#star-filled"></use></svg>
    </div>`}function k(e){let t=Math.round(10*Math.max(0,Math.min(5,Number(e)||0)));return t=t>=33&&t<=37?35:t>=38&&t<=42?40:t,{rateValue:t/10,rateIntValue:Math.floor(t/10),rateIsHalf:t%10>=5}}const M={feedbacks:[{_id:"682fbbdf8acbdf505592acdf",name:"Анна К.",date:"2024-12-01",descr:"Сайт дуже зручний, легко знайшла все, що потрібно. Обслуговування на висоті, меблі чудові!",rate:5},{_id:"682fbbdf8acbdf505592acf5",name:"Ірина Д.",date:"2025-01-15",descr:"Меблі для дитячої кімнати безпечні та яскраві. Дитина в захваті!",rate:4.5},{_id:"682fbbdf8acbdf505592acf8",name:"Людмила А.",date:"2025-01-21",descr:"Гардеробна система – це мрія. Тепер у нас повний порядок в речах.",rate:4.5},{_id:"682fbbdf8acbdf505592acfd",name:"Софія Г.",date:"2025-01-31",descr:"Крісло-кокон – ідеальне місце для релаксу. Дуже задоволена!",rate:4},{_id:"682fbbdf8acbdf505592ad17",name:"Дарія З.",date:"2025-03-24",descr:"Тумба для ванної кімнати дуже містка, все помістилося.",rate:5},{_id:"682fbbdf8acbdf505592ad24",name:"Роман Г.",date:"2025-04-19",descr:"Картина 'Абстракція Модерн' прикрасила нашу вітальню. Дуже задоволені.",rate:5},{_id:"682fbbdf8acbdf505592ad25",name:"Олена Л.",date:"2025-04-21",descr:"Менеджер допоміг з вибором, врахувавши всі наші побажання.",rate:5},{_id:"682fbbdf8acbdf505592ad32",name:"Ірина Г.",date:"2025-05-17",descr:"Вибір дитячих меблів дуже великий. Знайшли саме те, що шукали.",rate:4},{_id:"682fbbdf8acbdf505592ace3",name:"Наталія Л.",date:"2024-12-09",descr:"Замовляли кухню. Консультант допоміг з вибором, дизайн-проект безкоштовний. Дуже задоволені результатом!",rate:4.5},{_id:"682fbbdf8acbdf505592ace8",name:"Павло Р.",date:"2024-12-19",descr:"Шафа-купе ідеально вписалася в інтер'єр. Збірка зайняла небагато часу.",rate:5}],total:88,page:"1",limit:"10"};document.addEventListener("DOMContentLoaded",()=>{L(".feedback-data-container",M.feedbacks),q(),S()});function L(e,t){if(!t||!Array.isArray(t))return;const r=document.querySelector(e);if(!r)return;new URL("/goit-mebleria/assets/icons-yBS_w1Iq.svg",import.meta.url).href;const s=t.map(({_id:a,name:n,date:o,descr:c,rate:i})=>`
      <li class="swiper-slide feedback-item" data_id="${a}">
        <div class="feedback-rating" data-date="${o}" data-rate="${i}">${h(i)}</div>
        <p class="feedback-text">${c}</p>
        <p class="feedback-author">${n}</p>
      </li>`).join("");r.innerHTML=s}function q(){new l(".feedback-swiper",{modules:[u,f,b,m],direction:"horizontal",loop:!1,pagination:{el:".feedback-swiper-pagination",type:"bullets",clickable:!0},navigation:{prevEl:".feedback-swiper-button-prev",nextEl:".feedback-swiper-button-next"},slidePerView:1,breakpoints:{768:{slidesPerView:2,spaceBetween:24},1440:{slidesPerView:3,spaceBetween:24}},keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!1},mousewheel:{enabled:!0,forceToAxis:!0,invert:!1}})}function S(){const e=document.querySelector(".feedback-list");e&&g(".feedback-swiper-controls",e.childElementCount>0)}
//# sourceMappingURL=index.js.map
